export default [
  { "username": "becca",
    "display_name": "Becca",
    "type": "HUMAN",
    "bio": "I am a human",
    "_id": "001",
    "password": "123",
    "total_recommendations": 12,
    "total_contributions": 6},
  { "username": "hannah",
    "display_name": "Hannah",
    "type": "ALIEN",
    "bio": "I am an alien",
    "_id": "002",
    "password": "123",
    "total_likes": 10,
    "total_comments": 5},
  { "username": "sammi",
    "display_name": "Sammi",
    "type": "MODERATOR",
    "bio": "I am a moderator",
    "_id": "003",
    "password": "123",
    "total_actions_taken": 0},
]
